
server:
  port: 8765

spring:
  cloud:
    config:
      uri: http://${config-service:localhost}:8980
      fail-fast: true
      password: 1234
      username: root
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: one
          uri: 'lb://simple-service'
          predicates:
            - Path=/hello/world
            - Method=GET
        - id: hello
          uri: 'lb://simple-service'
          predicates:
            - Path=/hello
            - Method=GET
        - id: msg
          uri: 'lb://simple-service'
          predicates:
            - Path=/hello/msg
            - Method=GET
        - id: resource
          uri: 'lb://secured-service'
          predicates:
            - Path=/resource
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: msg
          uri: 'lb://openfeign-service'
          predicates:
            - Path=/hello/feign
            - Method=GET
        - id: eureka
          uri: 'http://localhost:8761'
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/
        - id: eureka-static
          uri: 'http://localhost:8761'
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: uaa
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email,resource.read
        provider:
          uaa:
            authorization-uri: http://localhost:8090/uaa/oauth/authorize
            token-uri: http://${uaa-server:localhost}:8090/uaa/oauth/token
            user-info-uri: http://${uaa-server:localhost}:8090/uaa/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://${uaa-server:localhost}:8090/uaa/token_keys


some:
  data:
    one: ${SPRING_DATA_FIRST:FirstData}